In [ ]:
import cv2
import numpy as np

img=cv2.imread('2.png',cv2.IMREAD_COLOR)

out=np.zeros(img.shape)

for k in range(img.shape[2]):
	int_min=np.amin(img[:,:,k])
	int_max=np.amax(img[:,:,k])
	x1=int_min
	y1=0
	x2=int_max
	y2=255
	m=float(y2-y1)/float(x2-x1)
	out[:,:,k]=img[:,:,k]*m
	out[:,:,k]=out[:,:,k]-(x1*m)


out=np.array(out, dtype = np.uint8)
print(img)
print(out)
cv2.imshow('image', img)
cv2.imshow('contrast expanded', out)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[254 251 246]
  [253 250 247]
  [252 250 246]
  ...
  [194 212 223]
  [190 208 219]
  [186 204 215]]

 [[254 251 247]
  [252 251 247]
  [252 251 247]
  ...
  [200 218 229]
  [198 216 227]
  [196 214 225]]

 [[252 251 247]
  [252 251 247]
  [252 251 247]
  ...
  [200 218 229]
  [199 217 228]
  [199 217 228]]

 ...

 [[ 86 112 126]
  [132 158 172]
  [150 176 192]
  ...
  [156 178 196]
  [152 172 190]
  [146 166 184]]

 [[ 37  63  77]
  [ 65  91 105]
  [ 84 109 125]
  ...
  [156 178 196]
  [149 169 187]
  [141 161 179]]

 [[102 128 142]
  [111 137 151]
  [129 154 170]
  ...
  [156 178 196]
  [147 167 185]
  [137 157 175]]]
[[[254 251 246]
  [253 250 247]
  [252 250 246]
  ...
  [194 212 223]
  [190 208 219]
  [186 204 215]]

 [[254 251 247]
  [252 251 247]
  [252 251 247]
  ...
  [200 218 229]
  [198 216 227]
  [196 214 225]]

 [[252 251 247]
  [252 251 247]
  [252 251 247]
  ...
  [200 218 229]
  [199 217 228]
  [199 217 228]]

 ...

 [[ 86 112 126]
  [132 158 172]
  [150 176 192]
  ..