In [ ]:
import cv2
import numpy as np

def invertor(value):
	return 255-value

img=cv2.imread('2.png',cv2.IMREAD_COLOR)

out=np.zeros(img.shape)
for i in range(img.shape[0]):
	for j in range(img.shape[1]):
		for k in range(img.shape[2]):
			out[i,j,k]=invertor(img[i,j,k])

out=np.array(out, dtype = np.uint8)

cv2.imshow('image', img)
print img
cv2.imshow('inverted', out)
print "\n\n\nthe changed matrices are:\n"
print out
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[254 251 246]
  [253 250 247]
  [252 250 246]
  ...
  [194 212 223]
  [190 208 219]
  [186 204 215]]

 [[254 251 247]
  [252 251 247]
  [252 251 247]
  ...
  [200 218 229]
  [198 216 227]
  [196 214 225]]

 [[252 251 247]
  [252 251 247]
  [252 251 247]
  ...
  [200 218 229]
  [199 217 228]
  [199 217 228]]

 ...

 [[ 86 112 126]
  [132 158 172]
  [150 176 192]
  ...
  [156 178 196]
  [152 172 190]
  [146 166 184]]

 [[ 37  63  77]
  [ 65  91 105]
  [ 84 109 125]
  ...
  [156 178 196]
  [149 169 187]
  [141 161 179]]

 [[102 128 142]
  [111 137 151]
  [129 154 170]
  ...
  [156 178 196]
  [147 167 185]
  [137 157 175]]]



the changed matrices are:

[[[  1   4   9]
  [  2   5   8]
  [  3   5   9]
  ...
  [ 61  43  32]
  [ 65  47  36]
  [ 69  51  40]]

 [[  1   4   8]
  [  3   4   8]
  [  3   4   8]
  ...
  [ 55  37  26]
  [ 57  39  28]
  [ 59  41  30]]

 [[  3   4   8]
  [  3   4   8]
  [  3   4   8]
  ...
  [ 55  37  26]
  [ 56  38  27]
  [ 56  38  27]]

 ...

 [[169 143 129]
  [123